FROM {{ registry }}{{ alt_image }}:{{ branch }}

MAINTAINER alt-cloud

{{ install_pakages("prometheus") }}

WORKDIR /var/lib/prometheus
USER prometheus
EXPOSE     9090
VOLUME     [ "/var/lib/prometheus" ]
ENTRYPOINT [ "/usr/bin/prometheus", "--config.file=/etc/prometheus/prometheus.yml"]
