FROM {{ registry }}{{ organization }}/base:{{ branch }}

MAINTAINER alt-cloud

{{ install_pakages(
    "python3-module-pip",
    "python3-module-setuptools",
    "python3-dev",
    "gcc",
) }}

CMD ["python3"]
