FROM {{ registry }}{{ alt_image }}:{{ branch }}

MAINTAINER alt-cloud

{{ install_pakages(
    "k8s-trivy-node-collector"
) }}

RUN ln -s /usr/bin/k8s-trivy-node-collector /usr/bin/node-collector

ENTRYPOINT ["node-collector"]
