FROM {{ registry }}{{ alt_image }}:{{ branch }}

MAINTAINER alt-cloud

{{ install_pakages("cert-manager") }}

RUN groupadd -r -g 1000 cert-manger && useradd --no-log-init -r -u 1000 -g cert-manger cert-manger

USER 1000

ENTRYPOINT ["/usr/bin/webhook"]
