FROM {{ registry }}{{ alt_image }}:{{ branch }}

MAINTAINER alt-cloud

{{ install_pakages("kubernetes-node") }}

RUN ln -s /usr/bin/kube-proxy /usr/local/bin/kube-proxy

ENTRYPOINT ["/usr/bin/kube-proxy"]
