FROM {{ registry }}{{ alt_image }}:{{ branch }}

MAINTAINER alt-cloud

RUN echo %_excludedocs 1 >> /etc/rpm/macros
{{ install_pakages("python3", "glibc-utils") }}
WORKDIR /usr/src/distroless
RUN mkdir file-lists
RUN useradd -m nonroot
COPY distroless-builder.py .
