FROM {{ registry }}{{ alt_image }}:{{ branch }}

MAINTAINER alt-cloud

{{ install_pakages("gitea", "openssh-server", "gosu") }}

ENV USER gitea
ENV HOME /var/lib/gitea
ENV GITEA_WORK_DIR /var/lib/gitea

WORKDIR /var/lib/gitea

COPY app.ini /etc/gitea/app.ini
COPY entrypoint.sh /entrypoint.sh

EXPOSE 3000
EXPOSE 2222

VOLUME ["/var/lib/gitea"]

ENTRYPOINT ["/entrypoint.sh"]
