FROM alt:sisyphus as installer

RUN apt-get update && \
    apt-get install -y apt-repo && \
    sh -c 'yes | apt-repo test 310153' && \
    apt-get remove -y apt-repo && \
    rm -f /var/cache/apt/archives/*.rpm \
          /var/cache/apt/*.bin \
          /var/lib/apt/lists/*.*

FROM scratch

COPY --from=installer /usr/bin/kubernetes-pause /pause

CMD ["/pause"]
