FROM {{ registry }}{{ organization }}/buildpack-deps-curl:{{ branch }}

MAINTAINER alt-cloud


{{ install_pakages(
    "git",
    "mercurial",
    "openssh-clients",
    "procps",
    "subversion"
) }}
